_G.lvim = _G.lvim or {}
lvim.toms = {
  plugins = {
    ["astrocore"] = { enabled = true },
    ["copilotchat"] = { enabled = true },
    ["copilot"] = { enabled = true },
    ["dap-python"] = { enabled = true },
    ["flit"] = { enabled = true },
    ["formatter"] = { enabled = true },
    ["glow"] = { enabled = true },
    ["goto-preview"] = { enabled = true },
    ["lazygit"] = { enabled = true },
    ["leap"] = { enabled = true },
    ["lspsaga"] = { enabled = true },
    ["monokai"] = { enabled = false },
    ["neogen"] = { enabled = true },
    ["nvim-gmove"] = { enabled = true },
    ["nvim-jdtl"] = { enabled = true },
    ["nvim-lastplace"] = { enabled = true },
    ["nvim-surround"] = { enabled = true },
    ["swenv"] = { enabled = true },
    ["symbols-outline"] = { enabled = true },
    ["targets"] = { enabled = true },
    ["telescope"] = { enabled = true },
    ["todo-comments"] = { enabled = true },
    ["undotree"] = { enabled = true },
    ["vim-tmux-navigator"] = { enabled = true },
    ["vim-translator"] = { enabled = true },
    ["kanagawa"] = { enabled = true },
    ["vscode"] = { enabled = true },
    ["wilder"] = { enabled = true },
    ["showkeys"] = { enabled = false },
    ["oil"] = { enabled = true },
    ["statusline"] = { enabled = true },
    ["noice"] = { enabled = true },
  }
}
